# Site settings
title: One Love to Rule Them All
email: pope410211@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onelovetorulethemall.com" # the base hostname & protocol for your site
twitter_username: pope410211
github_username:  pope410211

# Build settings
markdown: kramdown
